title: EtBook Documentation
description: Legal terms and documentation for EtBook mobile application
baseurl: "/Terms"
url: "https://bogaleb.github.io"

# Build settings
markdown: kramdown
theme: minima

# Enable GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Navigation
navigation:
  - title: Privacy Policy
    url: /docs/privacy-policy/
  - title: Terms of Service
    url: /docs/terms-of-service/
  - title: Support
    url: /docs/support/